use pest::Parser;
use pest_derive::Parser;

#[derive(Parser)]
#[grammar = "grammar.pest"]
pub struct JPortalParser;

// The Rule enum is automatically generated by pest_derive


// The Rule enum is automatically generated by pest_derive and available directly
// We can use it as Rule::database, Rule::identifier, etc.

// Data structures representing the parsed database
#[derive(Debug, Clone)]
pub struct Database {
    pub name: String,
    pub userid: String,
    pub password: String,
    pub flags: Vec<String>,
    pub package_name: Option<String>,
    pub output: Option<String>,
    pub imports: Vec<String>,
    pub server: String,
    pub schema: Option<String>,
    pub tables: Vec<Table>,
    pub views: Vec<View>,
}

#[derive(Debug, Clone)]
pub struct Table {
    pub name: String,
    pub alias: Option<String>,
    pub check: Option<String>,
    pub comments: Vec<String>,
    pub options: Vec<String>,
    pub fields: Vec<Field>,
    pub keys: Vec<Key>,
    pub links: Vec<Link>,
    pub grants: Vec<Grant>,
    pub views: Vec<View>,
    pub consts: Vec<Const>,
    pub procs: Vec<Proc>,
    pub parameters: Vec<Parameter>,
    pub is_import: bool,
    pub import_fields: Vec<String>,
    pub is_literal: bool,
    pub literal_name: String,
    pub start_line: Option<i32>,
    pub has_execute: bool,
    pub has_select: bool,
    pub has_delete: bool,
    pub has_insert: bool,
    pub has_update: bool,
    pub has_primary_key: bool,
    pub has_sequence: bool,
    pub has_sequence_returning: bool,
    pub has_identity: bool,
    pub has_std_procs: bool,
    pub has_big_xml: bool,
    pub has_big_json: bool,
}

impl Table {
    // Helper method to check if table has a field - matches JavaCC hasField()
    pub fn has_field(&self, field_name: &str) -> bool {
        self.fields.iter().any(|f| f.name == field_name)
    }
    
    // Helper method to set primary key on a field - matches JavaCC setPrimary()
    pub fn set_primary(&mut self, field_name: &str) {
        if let Some(field) = self.fields.iter_mut().find(|f| f.name == field_name) {
            field.is_primary = true;
        }
    }
    
    // Helper method to check if table has a procedure - matches JavaCC hasProc()
    pub fn has_proc(&self, proc: &Proc) -> bool {
        self.procs.iter().any(|p| p.name == proc.name)
    }
    
    // Helper method to check if field is nullable - matches JavaCC hasFieldAsNull()
    pub fn has_field_as_null(&self, field_name: &str) -> bool {
        if let Some(field) = self.fields.iter().find(|f| f.name == field_name) {
            field.is_null
        } else {
            true // Default to nullable if field not found
        }
    }
}

#[derive(Debug, Clone)]
pub struct Field {
    pub name: String,
    pub alias: Option<String>,
    pub field_type: FieldType,
    pub length: Option<i32>,
    pub precision: Option<i32>,
    pub scale: Option<i32>,
    pub is_null: bool,
    pub is_calc: bool,
    pub default_value: Option<String>,
    pub check_value: Option<String>,
    pub comments: Vec<String>,
    pub enums: Vec<Enum>,
    pub value_list: Vec<String>,
    pub is_literal: bool,
    pub literal_name: String,
    pub is_package_field: bool,
    pub is_sequence: bool,
    pub enum_type: Option<String>,
    pub lookup_name: Option<String>,
    pub enum_link: Option<String>,
    pub is_primary: bool,
    pub is_out: bool,  // For SPROC output fields
    pub is_in: bool,   // For input fields - matches JavaCC field.isIn
}

#[derive(Debug, Clone, PartialEq)]
pub enum FieldType {
    Blob,
    Boolean,
    Byte,
    Char,
    AnsiChar,
    WChar,
    WAnsiChar,
    Utf8,
    Short,
    Int,
    Long,
    Uid,
    Date,
    DateTime,
    Time,
    Timestamp,
    AutoTimestamp,
    Tlob,
    Xml,
    BigXml,
    Json,
    BigJson,
    UserStamp,
    Sequence,
    BigSequence,
    Identity,
    BigIdentity,
    Double,
    Float,
    Money,
    Lookup,
}

#[derive(Debug, Clone)]
pub struct Enum {
    pub name: String,
    pub value: i32,
}

#[derive(Debug, Clone)]
pub struct Key {
    pub name: String,
    pub is_unique: bool,
    pub is_primary: bool,
    pub fields: Vec<String>,
    pub options: Vec<String>,
}

impl Key {
    // Helper method to check if key has a field - matches JavaCC hasField()
    pub fn has_field(&self, field_name: &str) -> bool {
        self.fields.iter().any(|f| f == field_name)
    }
}

#[derive(Debug, Clone)]
pub struct Link {
    pub name: String,
    pub fields: Vec<String>,
    pub link_fields: Vec<String>,
    pub is_delete_cascade: bool,
    pub is_update_cascade: bool,
    pub options: Vec<String>,
}

impl Link {
    // Helper method to check if link has a field - matches JavaCC hasField()
    pub fn has_field(&self, field_name: &str) -> bool {
        self.fields.iter().any(|f| f == field_name)
    }
}

#[derive(Debug, Clone)]
pub struct Grant {
    pub perms: Vec<String>,
    pub users: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct View {
    pub name: String,
    pub users: Vec<String>,
    pub aliases: Vec<String>,
    pub lines: Vec<String>,
    pub start_line: Option<i32>,
}

impl View {
    // Helper method to check if view has a user - matches JavaCC hasUser()
    pub fn has_user(&self, user_name: &str) -> bool {
        self.users.iter().any(|u| u == user_name)
    }
    
    // Helper method to check if view has an alias - matches JavaCC hasAlias()
    pub fn has_alias(&self, alias_name: &str) -> bool {
        self.aliases.iter().any(|a| a == alias_name)
    }
}

#[derive(Debug, Clone)]
pub struct Proc {
    pub name: String,
    pub is_proc: bool,
    pub is_sproc: bool,
    pub is_built_in: bool,
    pub is_update: bool,
    pub is_single: bool,
    pub is_std: bool,
    pub has_returning: bool,
    pub use_std: bool,
    pub extends_std: bool,
    pub comments: Vec<String>,
    pub options: Vec<String>,
    pub inputs: Vec<Field>,
    pub outputs: Vec<Field>,
    pub lines: Vec<String>,
    pub fields: Vec<String>,
    pub start_line: Option<i32>,
    pub table: Option<String>,
    pub row_count: Option<i32>,
    // Additional fields for jNewProc functionality
    pub is_multiple_input: bool,
    pub no_rows: Option<i32>,
    pub has_updates: bool,
    pub is_sql: bool,
    pub dynamics: Vec<String>,
    pub dynamic_sizes: Vec<i32>,
    // Additional fields for data and IDL blocks
    pub is_data: bool,
    pub is_idl_code: bool,
    pub update_fields: Vec<String>,
    pub order_fields: Vec<Field>,
    pub dynamic_strung: Vec<bool>,
}

impl Proc {
    // Helper method to check if proc has an input field - matches JavaCC hasInput()
    pub fn has_input(&self, field_name: &str) -> bool {
        self.inputs.iter().any(|f| f.name == field_name)
    }
    
    // Helper method to check if proc has an output field - matches JavaCC hasOutput()
    pub fn has_output(&self, field_name: &str) -> bool {
        self.outputs.iter().any(|f| f.name == field_name)
    }
    
    // Helper method to get mutable input field - matches JavaCC getInput()
    pub fn get_input(&mut self, field_name: &str) -> Option<&mut Field> {
        self.inputs.iter_mut().find(|f| f.name == field_name)
    }
    
    // Helper method to check if proc has a field - matches JavaCC hasFields()
    pub fn has_fields(&self, field_name: &str) -> bool {
        self.fields.iter().any(|f| f == field_name)
    }
    
    // Helper method to check if proc has update fields - matches JavaCC hasUpdateFields()
    pub fn has_update_fields(&self, field_name: &str) -> bool {
        self.update_fields.iter().any(|f| f == field_name)
    }
    
    // Helper method to check if proc has order fields - matches JavaCC hasOrders()
    pub fn has_orders(&self, field_name: &str) -> bool {
        self.order_fields.iter().any(|f| f.name == field_name)
    }
    
    // Helper method to check if proc has dynamic variable - matches JavaCC hasDynamic()
    pub fn has_dynamic(&self, dynamic_name: &str) -> bool {
        self.dynamics.iter().any(|d| d == dynamic_name)
    }
    
    // Helper method to check placeholders - matches JavaCC checkPlaceHolders()
    pub fn check_place_holders(&mut self) {
        // Implementation would check for placeholder validation
        // For now, this is a stub to match the JavaCC interface
    }
}

#[derive(Debug, Clone)]
pub struct Parameter {
    pub title: Option<String>,
    pub is_view_only: bool,
    pub shows: Vec<String>,
    pub supplied: Vec<String>,
    pub cache_extras: Vec<String>,
    pub cache: Option<String>,
    pub reader: Option<String>,
    pub insert: Option<String>,
    pub update: Option<String>,
    pub delete: Option<String>,
}

#[derive(Debug, Clone)]
pub struct Const {
    pub name: String,
    pub values: Vec<ConstValue>,
}

#[derive(Debug, Clone)]
pub struct ConstValue {
    pub key: String,
    pub value: String,
}

// Parser implementation
pub fn parse_database(input: &str) -> Result<Database, Box<dyn std::error::Error>> {
    let pairs = JPortalParser::parse(Rule::database, input)?;
    
    for pair in pairs {
        match pair.as_rule() {
            Rule::database => {
                return parse_database_rule(pair);
            }
            _ => unreachable!(),
        }
    }
    
    Err("No database found".into())
}

fn parse_database_rule(pair: pest::iterators::Pair<Rule>) -> Result<Database, Box<dyn std::error::Error>> {
    let mut database = Database {
        name: String::new(),
        userid: String::new(),
        password: String::new(),
        flags: Vec::new(),
        package_name: None,
        output: None,
        imports: Vec::new(),
        server: String::new(),
        schema: None,
        tables: Vec::new(),
        views: Vec::new(),
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::database_name => {
                for name_pair in inner_pair.into_inner() {
                    database.name = parse_ident_or_string_from_pair(name_pair);
                }
            }
            Rule::flags_section => {
                for flag_pair in inner_pair.into_inner() {
                    if let Rule::string_literal = flag_pair.as_rule() {
                        database.flags.push(parse_string_literal(flag_pair.as_str()));
                    }
                }
            }
            Rule::package_section => {
                for pkg_pair in inner_pair.into_inner() {
                    if let Rule::package_ident = pkg_pair.as_rule() {
                        database.package_name = Some(pkg_pair.as_str().to_string());
                    }
                }
            }
            Rule::output_section => {
                for out_pair in inner_pair.into_inner() {
                    if let Rule::ident_or_string = out_pair.as_rule() {
                        database.output = Some(parse_ident_or_string(out_pair));
                    }
                }
            }
            Rule::import_section => {
                for imp_pair in inner_pair.into_inner() {
                    if let Rule::ident_or_string = imp_pair.as_rule() {
                        database.imports.push(parse_ident_or_string(imp_pair));
                    }
                }
            }
            Rule::connect_section => {
                parse_connect_section(inner_pair, &mut database)?;
            }
            Rule::tables_section => {
                parse_tables_section(inner_pair, &mut database)?;
            }
            _ => {}
        }
    }
    
    Ok(database)
}

// Enhanced string parsing - matches JavaCC jString() and fixString()
fn parse_jstring(input: &str) -> String {
    // Enhanced string literal parsing with fixString() behavior
    let trimmed = input.trim_matches('"').trim_matches('\'');
    
    // Process escape sequences like JavaCC fixString()
    let mut result = String::new();
    let mut chars = trimmed.chars().peekable();
    
    while let Some(ch) = chars.next() {
        if ch == '\\' {
            if let Some(&next_ch) = chars.peek() {
                match next_ch {
                    'n' => {
                        result.push('\n');
                        chars.next();
                    }
                    't' => {
                        result.push('\t');
                        chars.next();
                    }
                    'r' => {
                        result.push('\r');
                        chars.next();
                    }
                    '\\' => {
                        result.push('\\');
                        chars.next();
                    }
                    '"' => {
                        result.push('"');
                        chars.next();
                    }
                    '\'' => {
                        result.push('\'');
                        chars.next();
                    }
                    _ => {
                        // For any other character after \, just include both characters
                        result.push(ch);
                        result.push(chars.next().unwrap());
                    }
                }
            } else {
                result.push(ch);
            }
        } else {
            result.push(ch);
        }
    }
    
    result
}

// Enhanced identifier parsing - matches JavaCC jIdent() behavior
fn parse_ident_or_string_from_pair(pair: pest::iterators::Pair<Rule>) -> String {
    match pair.as_rule() {
        Rule::identifier => pair.as_str().to_string(),
        Rule::literal_identifier => {
            // Handle L'identifier' format - extract content between quotes
            let s = pair.as_str();
            if s.len() > 3 && (s.starts_with("L'") || s.starts_with("l'")) && s.ends_with('\'') {
                s[2..s.len()-1].to_string()
            } else {
                s.to_string()
            }
        }
        Rule::string_literal => pair.as_str().to_string(), // Keep quotes for consistency
        _ => pair.as_str().to_string(),
    }
}

fn parse_ident_or_string(pair: pest::iterators::Pair<Rule>) -> String {
    for inner_pair in pair.clone().into_inner() {
        return parse_ident_or_string_from_pair(inner_pair);
    }
    pair.as_str().to_string()
}

fn parse_connect_section(pair: pest::iterators::Pair<Rule>, database: &mut Database) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::server_clause => {
                for server_pair in inner_pair.into_inner() {
                    if let Rule::ident_or_string = server_pair.as_rule() {
                        database.server = parse_ident_or_string(server_pair);
                    }
                }
            }
            Rule::schema_clause => {
                for schema_pair in inner_pair.into_inner() {
                    if let Rule::ident_or_string = schema_pair.as_rule() {
                        database.schema = Some(parse_ident_or_string(schema_pair));
                    }
                }
            }
            Rule::userid_clause => {
                for userid_pair in inner_pair.into_inner() {
                    if let Rule::identifier = userid_pair.as_rule() {
                        database.userid = userid_pair.as_str().to_string();
                    }
                }
            }
            Rule::password_clause => {
                for password_pair in inner_pair.into_inner() {
                    if let Rule::identifier = password_pair.as_rule() {
                        database.password = password_pair.as_str().to_string();
                    }
                }
            }
            _ => {}
        }
    }
    Ok(())
}

// Enhanced tables parsing - matches JavaCC jTables() behavior
fn parse_tables_section(pair: pest::iterators::Pair<Rule>, database: &mut Database) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::table_definition => {
                let table = parse_table_definition(inner_pair)?;
                database.tables.push(table);
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_table_definition(pair: pest::iterators::Pair<Rule>) -> Result<Table, Box<dyn std::error::Error>> {
    let mut table = Table {
        name: String::new(),
        alias: None,
        check: None,
        comments: Vec::new(),
        options: Vec::new(),
        fields: Vec::new(),
        keys: Vec::new(),
        links: Vec::new(),
        grants: Vec::new(),
        views: Vec::new(),
        consts: Vec::new(),
        procs: Vec::new(),
        parameters: Vec::new(),
        is_import: false,
        import_fields: Vec::new(),
        is_literal: false,
        literal_name: String::new(),
        start_line: None,
        has_execute: false,
        has_select: false,
        has_delete: false,
        has_insert: false,
        has_update: false,
        has_primary_key: false,
        has_sequence: false,
        has_sequence_returning: false,
        has_identity: false,
        has_std_procs: false,
        has_big_xml: false,
        has_big_json: false,
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::table_section => {
                parse_table_section_into(inner_pair, &mut table)?;
            }
            Rule::table_import_section => {
                parse_table_import_section_into(inner_pair, &mut table)?;
                table.is_import = true;
            }
            Rule::const_section => {
                let const_item = parse_const_section(inner_pair)?;
                table.consts.push(const_item);
            }
            Rule::enhanced_grant_section => {
                let grant = parse_enhanced_grant_section(inner_pair, &mut table)?;
                table.grants.push(grant);
            }
            Rule::original_grant_section => {
                let grant = parse_original_grant_section(inner_pair)?;
                table.grants.push(grant);
            }
            Rule::enhanced_key_section => {
                let key = parse_enhanced_key_section(inner_pair, &mut table)?;
                table.keys.push(key);
            }
            Rule::original_key_section => {
                let key = parse_original_key_section(inner_pair)?;
                table.keys.push(key);
            }
            Rule::enhanced_link_section => {
                let link = parse_enhanced_link_section(inner_pair, &mut table)?;
                table.links.push(link);
            }
            Rule::original_link_section => {
                let link = parse_original_link_section(inner_pair)?;
                table.links.push(link);
            }
            Rule::enhanced_view_section => {
                let view = parse_enhanced_view_section(inner_pair)?;
                table.views.push(view);
            }
            Rule::proc_section => {
                let proc = parse_proc_section(inner_pair)?;
                table.procs.push(proc);
            }
            Rule::parm_section => {
                let parameter = parse_parm_section(inner_pair)?;
                table.parameters.push(parameter);
            }
            _ => {}
        }
    }
    
    Ok(table)
}

fn parse_table_section_into(pair: pest::iterators::Pair<Rule>, table: &mut Table) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                table.name = inner_pair.as_str().to_string();
            }
            Rule::alias_clause => {
                table.alias = Some(parse_alias_clause(inner_pair)?);
            }
            Rule::check_clause => {
                table.check = Some(parse_check_clause(inner_pair)?);
            }
            Rule::comment_clause => {
                table.comments.push(parse_comment_clause(inner_pair)?);
            }
            Rule::options_clause => {
                table.options = parse_options_clause(inner_pair)?;
            }
            Rule::field_def => {
                let field = parse_field_def(inner_pair)?;
                table.fields.push(field);
            }
            Rule::package_field_def => {
                let field = parse_package_field_def(inner_pair)?;
                table.fields.push(field);
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_table_import_section_into(pair: pest::iterators::Pair<Rule>, table: &mut Table) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::ident_or_string => {
                table.name = parse_ident_or_string(inner_pair);
            }
            Rule::field_import_list => {
                table.import_fields = parse_field_import_list(inner_pair)?;
            }
            Rule::alias_clause => {
                table.alias = Some(parse_alias_clause(inner_pair)?);
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_alias_clause(pair: pest::iterators::Pair<Rule>) -> Result<String, Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::ident_or_string = inner_pair.as_rule() {
            return Ok(parse_ident_or_string(inner_pair));
        }
    }
    Ok(String::new())
}

fn parse_check_clause(pair: pest::iterators::Pair<Rule>) -> Result<String, Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::string_literal = inner_pair.as_rule() {
            return Ok(parse_string_literal(inner_pair.as_str()));
        }
    }
    Ok(String::new())
}

fn parse_comment_clause(pair: pest::iterators::Pair<Rule>) -> Result<String, Box<dyn std::error::Error>> {
    for inner_pair in pair.clone().into_inner() {
        if let Rule::string_literal = inner_pair.as_rule() {
            return Ok(parse_string_literal(inner_pair.as_str()));
        }
    }
    Ok(pair.as_str().to_string())
}

fn parse_options_clause(pair: pest::iterators::Pair<Rule>) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut options = Vec::new();
    for inner_pair in pair.into_inner() {
        if let Rule::string_literal = inner_pair.as_rule() {
            options.push(parse_string_literal(inner_pair.as_str()));
        }
    }
    Ok(options)
}

fn parse_field_import_list(pair: pest::iterators::Pair<Rule>) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut fields = Vec::new();
    for inner_pair in pair.into_inner() {
        if let Rule::identifier = inner_pair.as_rule() {
            fields.push(inner_pair.as_str().to_string());
        }
    }
    Ok(fields)
}

fn parse_package_field_def(pair: pest::iterators::Pair<Rule>) -> Result<Field, Box<dyn std::error::Error>> {
    let mut field = Field {
        name: String::new(),
        alias: None,
        field_type: FieldType::Int,
        length: None,
        precision: None,
        scale: None,
        is_null: true, // fieldsNullByDefault in JavaCC
        is_calc: false,
        default_value: None,
        check_value: None,
        comments: Vec::new(),
        enums: Vec::new(),
        value_list: Vec::new(),
        is_literal: false,
        literal_name: String::new(),
        is_package_field: true,
        is_sequence: false,
        enum_type: None,
        lookup_name: None,
        enum_link: None,
        is_primary: false,
        is_out: false,
        is_in: false,
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::package_ident => {
                field.name = inner_pair.as_str().to_string();
                // TODO: Set is_literal and literal_name based on parsing
            }
            Rule::alias_clause => {
                field.alias = Some(parse_alias_clause(inner_pair)?);
            }
            Rule::field_type => {
                parse_field_type_into(inner_pair, &mut field)?;
            }
            Rule::package_field_modifiers => {
                parse_package_field_modifiers(inner_pair, &mut field)?;
            }
            Rule::comment_clause => {
                field.comments.push(parse_comment_clause(inner_pair)?);
            }
            _ => {}
        }
    }
    
    Ok(field)
}

fn parse_package_field_modifiers(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    let mut not_modifier = false;
    let mut expecting_default_value = false;
    let mut expecting_check_value = false;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::DEFAULT => {
                expecting_default_value = true;
            }
            Rule::string_literal => {
                if expecting_default_value {
                    field.default_value = Some(parse_string_literal(inner_pair.as_str()));
                    expecting_default_value = false;
                } else if expecting_check_value {
                    field.check_value = Some(parse_string_literal(inner_pair.as_str()));
                    expecting_check_value = false;
                }
            }
            Rule::NOT => {
                not_modifier = true;
            }
            Rule::NULL => {
                field.is_null = !not_modifier;
                not_modifier = false;
            }
            Rule::CALC => {
                field.is_calc = true;
            }
            Rule::CHECK => {
                expecting_check_value = true;
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_field_def(pair: pest::iterators::Pair<Rule>) -> Result<Field, Box<dyn std::error::Error>> {
    let mut field = Field {
        name: String::new(),
        alias: None,
        field_type: FieldType::Int,
        length: None,
        precision: None,
        scale: None,
        is_null: true,
        is_calc: false,
        default_value: None,
        check_value: None,
        comments: Vec::new(),
        enums: Vec::new(),
        value_list: Vec::new(),
        is_literal: false,
        literal_name: String::new(),
        is_package_field: false,
        is_sequence: false,
        enum_type: None,
        lookup_name: None,
        enum_link: None,
        is_primary: false,
        is_out: false,
        is_in: false,
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                field.name = inner_pair.as_str().to_string();
            }
            Rule::paren_alias_clause => {
                field.alias = Some(parse_paren_alias_clause(inner_pair)?);
            }
            Rule::field_type => {
                parse_field_type_into(inner_pair, &mut field)?;
            }
            Rule::field_modifiers => {
                parse_field_modifiers(inner_pair, &mut field)?;
            }
            Rule::lookup_type => {
                field.field_type = FieldType::Lookup;
                parse_lookup_type_into(inner_pair, &mut field)?;
            }
            Rule::comment_clause => {
                field.comments.push(parse_comment_clause(inner_pair)?);
            }
            _ => {}
        }
    }
    
    Ok(field)
}

fn parse_paren_alias_clause(pair: pest::iterators::Pair<Rule>) -> Result<String, Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::identifier = inner_pair.as_rule() {
            return Ok(inner_pair.as_str().to_string());
        }
    }
    Ok(String::new())
}

fn parse_field_type_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::BLOB => {
                field.field_type = FieldType::Blob;
                field.length = Some(0);
            }
            Rule::BOOLEAN => {
                field.field_type = FieldType::Boolean;
                field.length = Some(1);
            }
            Rule::BYTE => {
                field.field_type = FieldType::Byte;
                field.length = Some(1);
            }
            Rule::CHAR => {
                field.field_type = FieldType::Char;
                field.length = Some(1);
            }
            Rule::ANSICHAR => {
                field.field_type = FieldType::AnsiChar;
                field.length = Some(1);
            }
            Rule::WCHAR => {
                field.field_type = FieldType::WChar;
                field.length = Some(1);
            }
            Rule::WANSICHAR => {
                field.field_type = FieldType::WAnsiChar;
                field.length = Some(1);
            }
            Rule::UTF8 => {
                field.field_type = FieldType::Utf8;
                field.length = Some(1);
            }
            Rule::SHORT => {
                field.field_type = FieldType::Short;
                field.length = Some(2);
            }
            Rule::INT => {
                field.field_type = FieldType::Int;
                field.length = Some(4);
            }
            Rule::LONG => {
                field.field_type = FieldType::Long;
                field.length = Some(8);
            }
            Rule::UID => {
                field.field_type = FieldType::Uid;
                field.length = Some(16);
            }
            Rule::DATE => {
                field.field_type = FieldType::Date;
                field.length = Some(8);
            }
            Rule::DATETIME => {
                field.field_type = FieldType::DateTime;
                field.length = Some(14);
            }
            Rule::TIME => {
                field.field_type = FieldType::Time;
                field.length = Some(6);
            }
            Rule::TIMESTAMP => {
                field.field_type = FieldType::Timestamp;
                field.length = Some(14);
            }
            Rule::AUTOTIMESTAMP => {
                field.field_type = FieldType::AutoTimestamp;
                field.length = Some(14);
            }
            Rule::TLOB => {
                field.field_type = FieldType::Tlob;
                field.length = Some(0);
            }
            Rule::XML => {
                field.field_type = FieldType::Xml;
                field.length = Some(1000); // DEFAULT_XML
            }
            Rule::BIGXML => {
                field.field_type = FieldType::BigXml;
                field.length = Some(10000); // DEFAULT_BIG_XML
            }
            Rule::JSON => {
                field.field_type = FieldType::Json;
                field.length = Some(1000); // DEFAULT_JSON
            }
            Rule::BIGJSON => {
                field.field_type = FieldType::BigJson;
                field.length = Some(10000); // DEFAULT_BIG_JSON
            }
            Rule::USERSTAMP => {
                field.field_type = FieldType::UserStamp;
                field.length = Some(50);
            }
            Rule::SEQUENCE => {
                field.field_type = FieldType::Sequence;
                field.is_sequence = true;
                field.length = Some(4);
            }
            Rule::BIGSEQUENCE => {
                field.field_type = FieldType::BigSequence;
                field.is_sequence = true;
                field.length = Some(8);
            }
            Rule::IDENTITY => {
                field.field_type = FieldType::Identity;
                field.is_sequence = true;
                field.length = Some(4);
            }
            Rule::BIGIDENTITY => {
                field.field_type = FieldType::BigIdentity;
                field.is_sequence = true;
                field.length = Some(8);
            }
            Rule::DOUBLE => {
                field.field_type = FieldType::Double;
                field.length = Some(8);
            }
            Rule::FLOAT => {
                field.field_type = FieldType::Float;
                field.length = Some(8);
            }
            Rule::MONEY => {
                field.field_type = FieldType::Money;
                field.length = Some(8);
            }
            Rule::enhanced_char_size => {
                parse_enhanced_char_size_into(inner_pair, field)?;
            }
            Rule::enhanced_float_size => {
                parse_enhanced_float_size_into(inner_pair, field)?;
            }
            Rule::float_size => {
                parse_float_size_into(inner_pair, field)?;
            }
            Rule::enhanced_enum_value => {
                parse_enhanced_enum_value_into(inner_pair, field)?;
            }
            Rule::enhanced_char_list => {
                parse_enhanced_char_list_into(inner_pair, field)?;
            }
            Rule::enhanced_enum_char => {
                parse_enhanced_enum_char_into(inner_pair, field)?;
            }
            Rule::char_list => {
                parse_char_list_into(inner_pair, field)?;
            }
            Rule::enum_value => {
                parse_enum_value_into(inner_pair, field)?;
            }
            _ => {}
        }
    }
    Ok(())
}

// Enhanced char size parsing - matches jCharsize()
fn parse_enhanced_char_size_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::number = inner_pair.as_rule() {
            if let Ok(size) = inner_pair.as_str().parse::<i32>() {
                field.length = Some(size);
            }
        }
    }
    Ok(())
}

// Enhanced float size parsing - matches jFloatsize()
fn parse_enhanced_float_size_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    let mut numbers = Vec::new();
    for inner_pair in pair.into_inner() {
        if let Rule::number = inner_pair.as_rule() {
            if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                numbers.push(num);
            }
        }
    }
    
    if numbers.len() >= 2 {
        field.precision = Some(numbers[0]);
        field.scale = Some(numbers[1]);
    }
    Ok(())
}

// Original float size parsing for backward compatibility
fn parse_float_size_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    let mut numbers = Vec::new();
    for inner_pair in pair.into_inner() {
        if let Rule::number = inner_pair.as_rule() {
            if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                numbers.push(num);
            }
        }
    }
    
    if !numbers.is_empty() {
        field.precision = Some(numbers[0]);
        if numbers.len() > 1 {
            field.scale = Some(numbers[1]);
        }
    }
    Ok(())
}

// Enhanced enum value parsing - matches jEnumValue()
fn parse_enhanced_enum_value_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::LINK => {
                // Skip LINK keyword, next should be identifier
            }
            Rule::identifier => {
                if field.enum_link.is_none() {
                    field.enum_link = Some(inner_pair.as_str().to_string());
                }
            }
            Rule::enum_item => {
                let enum_item = parse_enum_item(inner_pair)?;
                field.enums.push(enum_item);
            }
            _ => {}
        }
    }
    Ok(())
}

// Enhanced char list parsing - matches jCharList()
fn parse_enhanced_char_list_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::identifier = inner_pair.as_rule() {
            field.value_list.push(inner_pair.as_str().to_string());
        }
    }
    Ok(())
}

// Enhanced enum char parsing - matches jEnumChar()
fn parse_enhanced_enum_char_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::number => {
                if let Ok(size) = inner_pair.as_str().parse::<i32>() {
                    field.length = Some(size);
                }
            }
            Rule::LINK => {
                // Skip LINK keyword, next should be identifier
            }
            Rule::identifier => {
                if field.enum_link.is_none() {
                    field.enum_link = Some(inner_pair.as_str().to_string());
                }
            }
            Rule::enum_char_item => {
                let enum_item = parse_enum_char_item(inner_pair)?;
                field.enums.push(enum_item);
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_enum_char_item(pair: pest::iterators::Pair<Rule>) -> Result<Enum, Box<dyn std::error::Error>> {
    let mut name = String::new();
    let mut value = 0;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                name = inner_pair.as_str().to_string();
            }
            Rule::number => {
                if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                    value = num;
                }
            }
            _ => {}
        }
    }
    
    Ok(Enum { name, value })
}

fn parse_field_modifiers(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    let mut not_modifier = false;
    let mut expecting_default_value = false;
    let mut expecting_check_value = false;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::DEFAULT => {
                expecting_default_value = true;
            }
            Rule::string_literal => {
                if expecting_default_value {
                    field.default_value = Some(parse_string_literal(inner_pair.as_str()));
                    expecting_default_value = false;
                } else if expecting_check_value {
                    field.check_value = Some(parse_string_literal(inner_pair.as_str()));
                    expecting_check_value = false;
                }
            }
            Rule::NOT => {
                not_modifier = true;
            }
            Rule::NULL => {
                field.is_null = !not_modifier;
                not_modifier = false;
            }
            Rule::CALC => {
                field.is_calc = true;
            }
            Rule::CHECK => {
                expecting_check_value = true;
            }
            Rule::lookup_type => {
                field.field_type = FieldType::Lookup;
                parse_lookup_type_into(inner_pair, field)?;
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_lookup_type_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::identifier = inner_pair.as_rule() {
            field.lookup_name = Some(inner_pair.as_str().to_string());
        }
    }
    Ok(())
}

fn parse_enum_value_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::enum_item = inner_pair.as_rule() {
            let enum_item = parse_enum_item(inner_pair)?;
            field.enums.push(enum_item);
        }
    }
    Ok(())
}

fn parse_enum_item(pair: pest::iterators::Pair<Rule>) -> Result<Enum, Box<dyn std::error::Error>> {
    let mut name = String::new();
    let mut value = 0;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                name = inner_pair.as_str().to_string();
            }
            Rule::number => {
                if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                    value = num;
                }
            }
            _ => {}
        }
    }
    
    Ok(Enum { name, value })
}

fn parse_char_list_into(pair: pest::iterators::Pair<Rule>, field: &mut Field) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::string_literal = inner_pair.as_rule() {
            field.value_list.push(parse_string_literal(inner_pair.as_str()));
        }
    }
    Ok(())
}

fn parse_const_section(pair: pest::iterators::Pair<Rule>) -> Result<Const, Box<dyn std::error::Error>> {
    let mut const_item = Const {
        name: String::new(),
        values: Vec::new(),
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                const_item.name = inner_pair.as_str().to_string();
            }
            Rule::const_value => {
                let const_value = parse_const_value(inner_pair)?;
                const_item.values.push(const_value);
            }
            _ => {}
        }
    }
    
    Ok(const_item)
}

fn parse_const_value(pair: pest::iterators::Pair<Rule>) -> Result<ConstValue, Box<dyn std::error::Error>> {
    let mut const_value = ConstValue {
        key: String::new(),
        value: String::new(),
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                const_value.key = inner_pair.as_str().to_string();
            }
            Rule::string_literal => {
                const_value.value = parse_string_literal(inner_pair.as_str());
            }
            _ => {}
        }
    }
    
    Ok(const_value)
}

// Enhanced grant section parsing - matches jGrant() and jPermission()
fn parse_enhanced_grant_section(pair: pest::iterators::Pair<Rule>, table: &mut Table) -> Result<Grant, Box<dyn std::error::Error>> {
    let mut grant = Grant {
        perms: Vec::new(),
        users: Vec::new(),
    };
    
    let mut parsing_users = false;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::permission => {
                if !parsing_users {
                    let perm = parse_permission(inner_pair, table)?;
                    grant.perms.push(perm);
                }
            }
            Rule::TO => {
                parsing_users = true;
            }
            Rule::non_keyword_identifier => {
                if parsing_users {
                    grant.users.push(inner_pair.as_str().to_string());
                }
            }
            _ => {}
        }
    }
    
    Ok(grant)
}

// Enhanced permission parsing - matches JavaCC jPermission() behavior
fn parse_permission(pair: pest::iterators::Pair<Rule>, table: &mut Table) -> Result<String, Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::ALL => {
                // Set all permission flags like JavaCC
                table.has_execute = true;
                table.has_select = true;
                table.has_delete = true;
                table.has_insert = true;
                table.has_update = true;
                return Ok("all".to_string());
            }
            Rule::DELETE => {
                table.has_delete = true;
                return Ok("delete".to_string());
            }
            Rule::INSERT => {
                table.has_insert = true;
                return Ok("insert".to_string());
            }
            Rule::SELECT => {
                table.has_select = true;
                return Ok("select".to_string());
            }
            Rule::UPDATE => {
                table.has_update = true;
                return Ok("update".to_string());
            }
            Rule::EXECUTE => {
                table.has_execute = true;
                return Ok("execute".to_string());
            }
            _ => {}
        }
    }
    Ok("unknown".to_string())
}

// Enhanced link section parsing - matches jLink() and jLinkColumn()
fn parse_enhanced_link_section(pair: pest::iterators::Pair<Rule>, table: &mut Table) -> Result<Link, Box<dyn std::error::Error>> {
    let mut link = Link {
        name: String::new(),
        fields: Vec::new(),
        link_fields: Vec::new(),
        is_delete_cascade: false,
        is_update_cascade: false,
        options: Vec::new(),
    };
    
    let mut all_identifiers = Vec::new();
    let mut seen_cascade_or_options = false;
    let mut parsing_link_fields = false;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::package_ident => {
                link.name = inner_pair.as_str().trim().to_string();
            }
            Rule::LEFTPAREN => {
                parsing_link_fields = true;
            }
            Rule::RIGHTPAREN => {
                parsing_link_fields = false;
            }
            Rule::non_keyword_identifier => {
                let field_name = inner_pair.as_str().to_string();
                
                if parsing_link_fields {
                    // This is a link field (in parentheses)
                    link.link_fields.push(field_name);
                } else {
                    // This is a regular field - apply jLinkColumn() validation
                    if !table.has_field(&field_name) {
                        eprintln!("Warning: {} field {} not present in table", link.name, field_name);
                    } else if link.has_field(&field_name) {
                        eprintln!("Warning: {} field {} already present in link", link.name, field_name);
                    } else {
                        link.fields.push(field_name);
                    }
                }
                all_identifiers.push(inner_pair.as_str().to_string());
            }
            Rule::DELETE => {
                link.is_delete_cascade = true;
                seen_cascade_or_options = true;
            }
            Rule::UPDATE => {
                link.is_update_cascade = true;
                seen_cascade_or_options = true;
            }
            Rule::CASCADE => {
                // CASCADE is handled by the DELETE/UPDATE rules
            }
            Rule::OPTIONS => {
                seen_cascade_or_options = true;
            }
            Rule::string_literal => {
                link.options.push(parse_string_literal(inner_pair.as_str()));
            }
            _ => {}
        }
    }
    
    // If we didn't parse fields through the validation logic above,
    // fall back to the original logic for backward compatibility
    if link.fields.is_empty() && !all_identifiers.is_empty() {
        if seen_cascade_or_options && all_identifiers.len() > 1 {
            let last_idx = all_identifiers.len() - 1;
            if link.link_fields.is_empty() {
                link.link_fields = all_identifiers[0..last_idx].to_vec();
            }
            link.fields = vec![all_identifiers[last_idx].clone()];
        } else {
            link.fields = all_identifiers;
        }
    }
    
    Ok(link)
}

// Enhanced view section parsing - matches jView(), jViewAlias(), jNewViewCode(), and jOldViewCode()
fn parse_enhanced_view_section(pair: pest::iterators::Pair<Rule>) -> Result<View, Box<dyn std::error::Error>> {
    let mut view = View {
        name: String::new(),
        users: Vec::new(),
        aliases: Vec::new(),
        lines: Vec::new(),
        start_line: None,
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                view.name = inner_pair.as_str().to_string();
                // Set start line if available (matches JavaCC view.start = t.beginLine)
                view.start_line = Some(1); // In a real implementation, you'd get this from the parser
            }
            Rule::TO => {
                // Skip TO keyword, next should be users
            }
            Rule::non_keyword_identifier => {
                let user_name = inner_pair.as_str().to_string();
                
                // Validation logic from JavaCC jView() -> jUser()
                if view.has_user(&user_name) {
                    eprintln!("Warning: {} user {} already present in view", view.name, user_name);
                } else {
                    view.users.push(user_name);
                }
            }
            Rule::OUTPUT => {
                // Skip OUTPUT keyword, next should be aliases
            }
            Rule::view_alias => {
                let _alias = parse_view_alias_with_validation(inner_pair, &mut view)?;
                // Alias is added in the validation function if valid
            }
            Rule::view_code => {
                parse_view_code_into(inner_pair, &mut view)?;
            }
            Rule::old_view_code => {
                parse_old_view_code_into(inner_pair, &mut view)?;
            }
            _ => {}
        }
    }
    
    Ok(view)
}

// Enhanced view alias parsing - matches JavaCC jViewAlias()
fn parse_view_alias_with_validation(pair: pest::iterators::Pair<Rule>, view: &mut View) -> Result<String, Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::identifier = inner_pair.as_rule() {
            let alias_name = inner_pair.as_str().to_string();
            
            // Validation logic from JavaCC jViewAlias()
            if view.has_alias(&alias_name) {
                eprintln!("Warning: {} alias {} already present in view", view.name, alias_name);
            } else {
                view.aliases.push(alias_name.clone());
            }
            
            return Ok(alias_name);
        }
    }
    Ok(String::new())
}

// Enhanced view code parsing - matches JavaCC jNewViewCode()
fn parse_view_code_into(pair: pest::iterators::Pair<Rule>, view: &mut View) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::codeline = inner_pair.as_rule() {
            let line = parse_codeline_enhanced(inner_pair)?;
            view.lines.push(line);
        }
    }
    Ok(())
}

// Enhanced old view code parsing - matches JavaCC jOldViewCode()
fn parse_old_view_code_into(pair: pest::iterators::Pair<Rule>, view: &mut View) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::raw_content = inner_pair.as_rule() {
            // Process raw content like JavaCC jOldViewCode() - split by lines and trim
            let content = inner_pair.as_str();
            for line in content.lines() {
                let trimmed_line = line.trim();
                if !trimmed_line.is_empty() {
                    view.lines.push(trimmed_line.to_string());
                }
            }
        }
    }
    Ok(())
}

// Enhanced codeline parsing - matches JavaCC jNewViewCode() CODELINE processing
fn parse_codeline_enhanced(pair: pest::iterators::Pair<Rule>) -> Result<String, Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if let Rule::string_literal = inner_pair.as_rule() {
            // Process like JavaCC: line = t.image.trim() with jString() processing
            let line = parse_jstring(inner_pair.as_str()).trim().to_string();
            return Ok(line);
        }
    }
    Ok(String::new())
}

fn parse_field_list(pair: pest::iterators::Pair<Rule>) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut fields = Vec::new();
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                fields.push(inner_pair.as_str().to_string());
            }
            _ => {}
        }
    }
    
    Ok(fields)
}

fn parse_proc_section(pair: pest::iterators::Pair<Rule>) -> Result<Proc, Box<dyn std::error::Error>> {
    let mut proc = Proc {
        name: String::new(),
        is_proc: false,
        is_sproc: false,
        is_built_in: false,
        is_update: false,
        is_single: false,
        is_std: false,
        has_returning: false,
        use_std: false,
        extends_std: false,
        comments: Vec::new(),
        options: Vec::new(),
        inputs: Vec::new(),
        outputs: Vec::new(),
        lines: Vec::new(),
        fields: Vec::new(),
        start_line: Some(1), // Set start line (in real implementation, get from parser position)
        table: None,
        row_count: None,
        // Additional fields for jNewProc functionality
        is_multiple_input: false,
        no_rows: None,
        has_updates: false,
        is_sql: false,
        dynamics: Vec::new(),
        dynamic_sizes: Vec::new(),
        // Additional fields for data and IDL blocks
        is_data: false,
        is_idl_code: false,
        update_fields: Vec::new(),
        order_fields: Vec::new(),
        dynamic_strung: Vec::new(),
    };
    
    let mut in_data_block = false;
    let mut in_idl_block = false;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::PROC => {
                proc.is_proc = true;
            }
            Rule::SPROC => {
                proc.is_sproc = true;
            }
            Rule::SQLDATA => {
                proc.is_data = true;
                in_data_block = true;
            }
            Rule::IDLCODE => {
                proc.is_idl_code = true;
                in_idl_block = true;
            }
            Rule::ENDDATA => {
                // Removed - no longer supporting old DATA/ENDDATA blocks
            }
            Rule::data_line => {
                if in_data_block {
                    let line = inner_pair.as_str().trim().to_string();
                    proc.lines.push(line);
                }
            }
            Rule::idl_line => {
                if in_idl_block {
                    let line = inner_pair.as_str().trim().to_string();
                    if !line.is_empty() {
                        proc.lines.push(line);
                    }
                }
            }
            Rule::identifier => {
                if proc.name.is_empty() && !in_data_block && !in_idl_block {
                    proc.name = inner_pair.as_str().to_string();
                }
            }
            Rule::INSERT => {
                proc.name = "Insert".to_string();
                proc.is_built_in = true;
            }
            Rule::RETURNING => {
                proc.has_returning = true;
            }
            Rule::UPDATE => {
                if proc.name.is_empty() {
                    proc.name = "Update".to_string();
                    proc.is_built_in = true;
                    proc.is_update = true;
                }
            }
            Rule::UPDATEFOR => {
                proc.name = "UpdateFor".to_string();
                proc.is_built_in = true;
                proc.is_update = true;
            }
            Rule::UPDATEBY => {
                proc.name = "UpdateBy".to_string();
                proc.is_built_in = true;
                proc.is_update = true;
            }
            Rule::BULKINSERT => {
                proc.name = "BulkInsert".to_string();
                proc.is_built_in = true;
            }
            Rule::MAXTMSTAMP => {
                proc.name = "MaxTmStamp".to_string();
                proc.is_built_in = true;
            }
            Rule::BULKUPDATE => {
                proc.name = "BulkUpdate".to_string();
                proc.is_built_in = true;
                proc.is_update = true;
            }
            Rule::DELETEONE => {
                proc.name = "DeleteOne".to_string();
                proc.is_built_in = true;
            }
            Rule::DELETEALL => {
                proc.name = "DeleteAll".to_string();
                proc.is_built_in = true;
            }
            Rule::DELETEBY => {
                proc.name = "DeleteBy".to_string();
                proc.is_built_in = true;
            }
            Rule::SELECTONE => {
                proc.name = "SelectOne".to_string();
                proc.is_built_in = true;
                proc.is_single = true;
            }
            Rule::SELECTONEBY => {
                proc.name = "SelectOneBy".to_string();
                proc.is_built_in = true;
                proc.is_single = true;
            }
            Rule::SELECTBY => {
                proc.name = "SelectBy".to_string();
                proc.is_built_in = true;
            }
            Rule::SELECTALL => {
                proc.name = "SelectAll".to_string();
                proc.is_built_in = true;
            }
            Rule::COUNT => {
                proc.name = "Count".to_string();
                proc.is_built_in = true;
            }
            Rule::EXISTS => {
                proc.name = "Exists".to_string();
                proc.is_built_in = true;
            }
            Rule::MERGE => {
                proc.name = "Merge".to_string();
                proc.is_built_in = true;
            }
            Rule::STANDARD => {
                proc.is_std = true;
            }
            Rule::AS => {
                // Handle AS clause for custom names
            }
            Rule::custom_select_proc => {
                parse_custom_select_proc_into(inner_pair, &mut proc)?;
            }
            Rule::user_proc => {
                parse_user_proc_into(inner_pair, &mut proc)?;
            }
            Rule::proc_column => {
                let field_name = parse_proc_column(inner_pair)?;
                proc.fields.push(field_name);
            }
            Rule::row_count => {
                proc.row_count = parse_row_count(inner_pair)?;
            }
            Rule::OPTIONS => {
                // Skip the keyword, options will be parsed separately
            }
            Rule::string_literal => {
                // This could be an option value or data content
                if in_data_block || in_idl_block {
                    let line = parse_string_literal(inner_pair.as_str());
                    proc.lines.push(line);
                } else {
                    let line = parse_string_literal(inner_pair.as_str());
                    println!("Processing string_literal: '{}'", line);
                    println!("  in_data_block: {}, in_idl_block: {}", in_data_block, in_idl_block);
                    println!("  proc.name: '{}', proc.is_built_in: {}, proc.extends_std: {}", proc.name, proc.is_built_in, proc.extends_std);
                    println!("  line.contains('&'): {}", line.contains('&'));
                    
                    // Check if this is SQL code with dynamic variables
                    if line.contains('&') && (proc.extends_std || !proc.is_built_in) {
                        println!("  -> Processing as dynamic SQL");
                        let processed_line = parse_dynamics(&line, &mut proc)?;
                        proc.lines.push(processed_line);
                    } else if proc.name.is_empty() || proc.is_built_in {
                        println!("  -> Adding as option");
                        // This is likely an option value
                        proc.options.push(line);
                    } else {
                        println!("  -> Adding as regular SQL line");
                        // This is likely SQL code without dynamic variables
                        proc.lines.push(line);
                    }
                }
            }
            Rule::field_def => {
                let field = parse_field_def(inner_pair)?;
                proc.outputs.push(field);
            }
            _ => {
                // Handle other rules as needed
            }
        }
    }
    
    Ok(proc)
}

fn parse_proc_update_by_column(pair: pest::iterators::Pair<Rule>) -> Result<String, Box<dyn std::error::Error>> {
    Ok(pair.as_str().to_string())
}

fn parse_proc_returning_column(pair: pest::iterators::Pair<Rule>) -> Result<String, Box<dyn std::error::Error>> {
    Ok(pair.as_str().to_string())
}

fn parse_order_column(pair: pest::iterators::Pair<Rule>) -> Result<String, Box<dyn std::error::Error>> {
    Ok(pair.as_str().to_string())
}

fn parse_row_count(pair: pest::iterators::Pair<Rule>) -> Result<Option<i32>, Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        if inner_pair.as_rule() == Rule::number {
            return Ok(Some(inner_pair.as_str().parse().unwrap_or(0)));
        }
    }
    Ok(None)
}

fn parse_original_grant_section(pair: pest::iterators::Pair<Rule>) -> Result<Grant, Box<dyn std::error::Error>> {
    let mut grant = Grant {
        perms: Vec::new(),
        users: Vec::new(),
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                grant.perms.push(inner_pair.as_str().to_string());
            }
            Rule::field_list => {
                grant.users = parse_field_list(inner_pair)?;
            }
            _ => {}
        }
    }
    
    Ok(grant)
}

fn parse_original_key_section(pair: pest::iterators::Pair<Rule>) -> Result<Key, Box<dyn std::error::Error>> {
    let mut key = Key {
        name: String::new(),
        is_unique: false,
        is_primary: false,
        fields: Vec::new(),
        options: Vec::new(),
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                key.name = inner_pair.as_str().to_string();
            }
            Rule::field_list => {
                key.fields = parse_field_list(inner_pair)?;
            }
            _ => {}
        }
    }
    
    Ok(key)
}

fn parse_original_link_section(pair: pest::iterators::Pair<Rule>) -> Result<Link, Box<dyn std::error::Error>> {
    let mut link = Link {
        name: String::new(),
        fields: Vec::new(),
        link_fields: Vec::new(),
        is_delete_cascade: false,
        is_update_cascade: false,
        options: Vec::new(),
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                link.name = inner_pair.as_str().to_string();
            }
            Rule::field_list => {
                link.fields = parse_field_list(inner_pair)?;
                link.link_fields = link.fields.clone(); // For backward compatibility
            }
            _ => {}
        }
    }
    
    Ok(link)
}

fn parse_parm_section(pair: pest::iterators::Pair<Rule>) -> Result<Parameter, Box<dyn std::error::Error>> {
    let mut parameter = Parameter {
        title: None,
        is_view_only: false,
        shows: Vec::new(),
        supplied: Vec::new(),
        cache_extras: Vec::new(),
        cache: None,
        reader: None,
        insert: None,
        update: None,
        delete: None,
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::parm_body => {
                // Simple parameter parsing for now
            }
            _ => {}
        }
    }
    
    Ok(parameter)
}

// Enhanced key section parsing - matches jKey() and jColumn()
fn parse_enhanced_key_section(pair: pest::iterators::Pair<Rule>, table: &mut Table) -> Result<Key, Box<dyn std::error::Error>> {
    let mut key = Key {
        name: String::new(),
        is_unique: false,
        is_primary: false,
        fields: Vec::new(),
        options: Vec::new(),
    };
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                key.name = inner_pair.as_str().to_string();
            }
            Rule::OPTIONS => {
                // Skip OPTIONS keyword, next should be string literals
            }
            Rule::string_literal => {
                key.options.push(parse_string_literal(inner_pair.as_str()));
            }
            Rule::key_modifier => {
                parse_key_modifier_into(inner_pair, &mut key)?;
            }
            Rule::non_keyword_identifier => {
                let field_name = inner_pair.as_str().to_string();
                
                // Validation logic from JavaCC jColumn()
                if !table.has_field(&field_name) {
                    eprintln!("Warning: {} field {} not present in table", key.name, field_name);
                } else if key.has_field(&field_name) {
                    eprintln!("Warning: {} field {} already present in key", key.name, field_name);
                } else {
                    // Set primary key on field if this is a primary key
                    if key.is_primary {
                        table.set_primary(&field_name);
                    }
                    key.fields.push(field_name);
                }
            }
            _ => {}
        }
    }
    
    if key.is_primary {
        table.has_primary_key = true;
    }
    
    Ok(key)
}

// Enhanced key modifier parsing - matches JavaCC jModifier() behavior
fn parse_key_modifier_into(pair: pest::iterators::Pair<Rule>, key: &mut Key) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::UNIQUE => {
                key.is_unique = true;
            }
            Rule::PRIMARY => {
                key.is_primary = true;
                // Note: table.has_primary_key is set in parse_enhanced_key_section
            }
            _ => {}
        }
    }
    Ok(())
}

// Enhanced string literal parsing - matches JavaCC fixString() behavior
fn parse_string_literal(s: &str) -> String {
    // Use the enhanced jString() processing for consistency
    parse_jstring(s)
}

fn parse_input_type_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc, table: &Table) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::LEFTPAREN => {
                // Skip opening parenthesis
            }
            Rule::MULTIPLE => {
                proc.is_multiple_input = true;
            }
            Rule::number => {
                if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                    proc.no_rows = Some(num);
                    proc.is_multiple_input = true;
                }
            }
            Rule::STANDARD => {
                // Add all table fields as inputs - matches JavaCC behavior
                for field in &table.fields {
                    let mut input_field = field.clone();
                    input_field.is_in = true;
                    proc.inputs.push(input_field);
                }
            }
            Rule::RIGHTPAREN => {
                // Skip closing parenthesis
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_output_type_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc, table: &Table) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::LEFTPAREN => {
                // Skip opening parenthesis
            }
            Rule::SINGLE => {
                proc.is_single = true;
            }
            Rule::UPDATE => {
                proc.has_updates = true;
            }
            Rule::number => {
                if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                    proc.no_rows = Some(num);
                }
            }
            Rule::STANDARD => {
                // Add all table fields as outputs - matches JavaCC behavior
                for field in &table.fields {
                    let mut output_field = field.clone();
                    output_field.is_out = true;
                    proc.outputs.push(output_field);
                }
            }
            Rule::RIGHTPAREN => {
                // Skip closing parenthesis
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_old_code_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::SQL => {
                proc.is_sql = true;
            }
            Rule::CODE => {
                // Skip CODE keyword
            }
            Rule::ENDCODE => {
                // Skip ENDCODE keyword
            }
            Rule::old_code_content => {
                // Process the entire CODE content for dynamic variables
                let content = inner_pair.as_str();
                // Split into lines and process each line
                for line in content.lines() {
                    let line = line.trim();
                    if !line.is_empty() {
                        let processed_line = parse_dynamics(line, proc)?;
                        if !processed_line.trim().is_empty() {
                            proc.lines.push(processed_line);
                        }
                    }
                }
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_dynamic_identifier_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    let mut identifier = String::new();
    let mut size = 256; // Default size matches JavaCC jOptSize()
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                identifier = inner_pair.as_str().to_string();
            }
            Rule::opt_size => {
                size = parse_opt_size(inner_pair)?;
            }
            _ => {}
        }
    }
    
    // Add dynamic variable if not already present - matches JavaCC logic
    if !proc.has_dynamic(&identifier) {
        if proc.extends_std {
            proc.use_std = false;
        }
        proc.dynamics.push(identifier.clone());
        proc.dynamic_sizes.push(size);
        proc.dynamic_strung.push(false); // Default to not strung
    }
    
    Ok(())
}

fn parse_opt_size(pair: pest::iterators::Pair<Rule>) -> Result<i32, Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::number => {
                return Ok(inner_pair.as_str().parse::<i32>()?);
            }
            _ => {}
        }
    }
    Ok(256) // Default size
}

fn parse_new_code_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::SQLCODE => {
                // Skip SQLCODE keyword
            }
            Rule::ENDSQLCODE => {
                // Skip ENDSQLCODE keyword
            }
            Rule::sqlcode_content => {
                // Process the entire SQL content for dynamic variables
                let content = inner_pair.as_str();
                // Split into lines and process each line
                for line in content.lines() {
                    let line = line.trim();
                    if !line.is_empty() {
                        let processed_line = parse_dynamics(line, proc)?;
                        proc.lines.push(processed_line);
                    }
                }
            }
            _ => {}
        }
    }
    Ok(())
}

// Enhanced dynamic SQL parsing - matches JavaCC parseDynamics() function
fn parse_dynamics(input: &str, proc: &mut Proc) -> Result<String, Box<dyn std::error::Error>> {
    let mut result = String::new();
    let mut chars = input.chars().peekable();
    
    while let Some(ch) = chars.next() {
        if ch == '&' {
            // Found dynamic variable marker
            let mut var_name = String::new();
            let mut size = 256;
            let mut strung = false;
            
            // Check for string marker
            if chars.peek() == Some(&'\'') {
                strung = true;
                chars.next(); // consume '
            }
            
            // Read variable name
            while let Some(&next_ch) = chars.peek() {
                if next_ch.is_alphanumeric() || next_ch == '_' || next_ch == '(' || next_ch == ')' {
                    var_name.push(chars.next().unwrap());
                } else {
                    break;
                }
            }
            
            // Check for closing string marker
            if strung && chars.peek() == Some(&'\'') {
                chars.next(); // consume '
            }
            
            // Parse size specification if present
            if let Some(paren_pos) = var_name.find('(') {
                if let Some(close_paren_pos) = var_name.find(')') {
                    if close_paren_pos > paren_pos {
                        let size_str = &var_name[paren_pos + 1..close_paren_pos];
                        if let Ok(parsed_size) = size_str.parse::<i32>() {
                            size = parsed_size;
                        }
                        var_name = var_name[..paren_pos].to_string();
                    }
                }
            }
            
            // Add dynamic variable if not already present
            if !proc.has_dynamic(&var_name) {
                if proc.extends_std {
                    proc.use_std = false;
                }
                proc.dynamics.push(var_name.clone());
                proc.dynamic_sizes.push(size);
                proc.dynamic_strung.push(strung);
            }
            
            // Add placeholder for dynamic variable in the line
            result.push_str(&format!("${}", var_name));
        } else {
            result.push(ch);
        }
    }
    
    Ok(result)
}

// Enhanced procedure column parsing with JavaCC validation - matches jProcColumn()
fn parse_proc_column_with_validation(field_name: &str, proc: &mut Proc, table: &Table) -> Result<(), Box<dyn std::error::Error>> {
    if !table.has_field(field_name) {
        eprintln!("Warning: {} field {} not present in table", proc.name, field_name);
    } else if proc.fields.contains(&field_name.to_string()) {
        eprintln!("Warning: {} field {} already present", proc.name, field_name);
    } else if proc.has_input(field_name) {
        eprintln!("Warning: {} field {} cannot be set as well, already present as input", proc.name, field_name);
    } else {
        proc.fields.push(field_name.to_string());
    }
    Ok(())
}

// Enhanced procedure returning column parsing - matches jProcReturningColumn()
fn parse_proc_returning_column_with_validation(field_name: &str, proc: &mut Proc, table: &Table) -> Result<(), Box<dyn std::error::Error>> {
    if !table.has_field(field_name) {
        eprintln!("Warning: {} field {} not present in table", proc.name, field_name);
    } else if proc.has_output(field_name) {
        eprintln!("Warning: {} output {} already present", proc.name, field_name);
    } else {
        // In JavaCC, this adds table.getField(s) to proc.outputs
        // For now, we'll create a basic field from the table field
        if let Some(table_field) = table.fields.iter().find(|f| f.name == field_name) {
            proc.outputs.push(table_field.clone());
        }
    }
    Ok(())
}

// Enhanced order column parsing - matches jOrderColumn()
fn parse_order_column_with_validation(field_name: &str, proc: &mut Proc, table: &Table) -> Result<(), Box<dyn std::error::Error>> {
    if !table.has_field(field_name) {
        eprintln!("Warning: {} field {} not present in table", proc.name, field_name);
    } else if proc.fields.contains(&field_name.to_string()) {
        eprintln!("Warning: {} field {} already present", proc.name, field_name);
    } else {
        // In JavaCC, this adds table.getField(s) to proc.orderFields
        // We'll add it to a separate order fields collection
        proc.fields.push(field_name.to_string());
    }
    Ok(())
}

// Enhanced update by column parsing - matches jProcUpdateByColumn()
fn parse_proc_update_by_column_with_validation(field_name: &str, proc: &mut Proc, table: &Table) -> Result<(), Box<dyn std::error::Error>> {
    if !table.has_field(field_name) {
        eprintln!("Warning: {} field {} not present in table", proc.name, field_name);
    } else if proc.fields.contains(&field_name.to_string()) {
        eprintln!("Warning: {} field {} already present", proc.name, field_name);
    } else {
        // In JavaCC, this adds to proc.updateFields
        // We'll add it to the main fields collection
        proc.fields.push(field_name.to_string());
    }
    Ok(())
}

// Enhanced comment parsing - matches jComment()
fn parse_jcomment(comment_text: &str) -> String {
    let mut s = comment_text.to_string();
    
    // Remove leading asterisks
    while s.starts_with('*') {
        s = s[1..].to_string();
    }
    
    // Find first newline or carriage return
    if let Some(n) = s.find('\r') {
        s = s[..n].to_string();
    } else if let Some(n) = s.find('\n') {
        s = s[..n].to_string();
    }
    
    s.trim().to_string()
}

// Enhanced row count parsing - matches jRowCount()
fn parse_jrow_count(pair: pest::iterators::Pair<Rule>) -> Result<i32, Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::number => {
                return inner_pair.as_str().parse::<i32>()
                    .map_err(|e| format!("Failed to parse row count: {}", e).into());
            }
            _ => {}
        }
    }
    Err("No number found in row count".into())
}

fn parse_new_data_block_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    proc.is_data = true;
    proc.is_idl_code = false;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::data_line => {
                let line_content = inner_pair.as_str().trim();
                if !line_content.is_empty() {
                    proc.lines.push(line_content.to_string());
                }
            }
            _ => {}
        }
    }
    
    Ok(())
}

fn parse_idl_code_block_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    proc.is_idl_code = true;
    proc.is_data = false;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::IDLCODE => {
                // Skip IDLCODE keyword
            }
            Rule::idl_line => {
                let line_content = inner_pair.as_str().trim();
                if !line_content.is_empty() {
                    proc.lines.push(line_content.to_string());
                }
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_custom_select_proc_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    proc.extends_std = true;
    proc.use_std = true;
    
    let mut in_input_section = false;
    let mut in_output_section = false;
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::SELECT => {
                // Skip SELECT keyword
            }
            Rule::LEFTPAREN => {
                // Skip opening parenthesis
            }
            Rule::STANDARD => {
                proc.is_std = true;
            }
            Rule::RIGHTPAREN => {
                // Skip closing parenthesis
            }
            Rule::INPUT => {
                in_input_section = true;
                in_output_section = false;
            }
            Rule::enhanced_input_type => {
                // For now, parse without table context - will need to be enhanced later
                parse_enhanced_input_type_into_simple(inner_pair, proc)?;
            }
            Rule::OUTPUT => {
                in_input_section = false;
                in_output_section = true;
            }
            Rule::enhanced_output_type => {
                // For now, parse without table context - will need to be enhanced later
                parse_enhanced_output_type_into_simple(inner_pair, proc)?;
            }
            Rule::field_def => {
                let field = parse_field_def(inner_pair)?;
                if in_input_section {
                    proc.inputs.push(field);
                } else if in_output_section {
                    proc.outputs.push(field);
                }
            }
            Rule::new_code => {
                parse_new_code_into(inner_pair, proc)?;
            }
            Rule::old_code => {
                parse_old_code_into(inner_pair, proc)?;
            }
            Rule::string_literal => {
                let sql_content = parse_string_literal(inner_pair.as_str());
                if sql_content.contains('&') {
                    let processed_sql = parse_dynamics(&sql_content, proc)?;
                    if !processed_sql.is_empty() {
                        proc.lines.push(processed_sql);
                    }
                } else {
                    proc.lines.push(sql_content);
                }
            }
            _ => {
                // Skip other rules
            }
        }
    }
    
    Ok(())
}

fn parse_user_proc_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    proc.is_built_in = false;
    
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::STANDARD => {
                proc.extends_std = true;
                proc.use_std = true;
                proc.is_std = true;
            }
            Rule::comment_clause => {
                let comment = parse_comment_clause(inner_pair)?;
                proc.comments.push(comment);
            }
            Rule::OPTIONS => {
                // Skip OPTIONS keyword
            }
            Rule::string_literal => {
                proc.options.push(parse_string_literal(inner_pair.as_str()));
            }
            Rule::INPUT => {
                // Skip INPUT keyword
            }
            Rule::enhanced_input_type => {
                // For now, parse without table context - will need to be enhanced later
                parse_enhanced_input_type_into_simple(inner_pair, proc)?;
            }
            Rule::INOUT => {
                // Skip INOUT keyword
            }
            Rule::OUTPUT => {
                // Skip OUTPUT keyword
            }
            Rule::enhanced_output_type => {
                // For now, parse without table context - will need to be enhanced later
                parse_enhanced_output_type_into_simple(inner_pair, proc)?;
            }
            Rule::field_def => {
                let mut field = parse_field_def(inner_pair)?;
                // Determine if this is input, output, or both based on context
                field.is_in = true; // Default to input for user procedures
                proc.inputs.push(field);
            }
            Rule::old_code => {
                parse_old_code_into(inner_pair, proc)?;
            }
            Rule::new_code => {
                parse_new_code_into(inner_pair, proc)?;
            }
            _ => {}
        }
    }
    
    Ok(())
}

fn parse_enhanced_input_type_into_simple(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::LEFTPAREN => {
                // Skip opening parenthesis
            }
            Rule::MULTIPLE => {
                proc.is_multiple_input = true;
            }
            Rule::number => {
                if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                    proc.no_rows = Some(num);
                    proc.is_multiple_input = true;
                }
            }
            Rule::STANDARD => {
                // Set flags for STANDARD - actual field addition needs table context
                proc.extends_std = true;
                proc.use_std = true;
            }
            Rule::RIGHTPAREN => {
                // Skip closing parenthesis
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_enhanced_output_type_into_simple(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::LEFTPAREN => {
                // Skip opening parenthesis
            }
            Rule::SINGLE => {
                proc.is_single = true;
            }
            Rule::UPDATE => {
                proc.has_updates = true;
            }
            Rule::number => {
                if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                    proc.no_rows = Some(num);
                }
            }
            Rule::STANDARD => {
                // Set flags for STANDARD - actual field addition needs table context
                proc.extends_std = true;
                proc.use_std = true;
            }
            Rule::RIGHTPAREN => {
                // Skip closing parenthesis
            }
            _ => {}
        }
    }
    Ok(())
}

fn parse_proc_column(pair: pest::iterators::Pair<Rule>) -> Result<String, Box<dyn std::error::Error>> {
    Ok(pair.as_str().to_string())
}

// JavaCC-style jInputType function - matches JavaCC exactly
fn parse_j_input_type_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc, table: &Table) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::LEFTPAREN => {
                // Skip opening parenthesis
            }
            Rule::MULTIPLE => {
                // LOOKAHEAD(2) <LEFTPAREN> <MULTIPLE> <RIGHTPAREN>
                proc.is_multiple_input = true;
            }
            Rule::number => {
                // LOOKAHEAD(2) <LEFTPAREN> n = jNumber() <RIGHTPAREN>
                if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                    proc.no_rows = Some(num);
                    proc.is_multiple_input = true;
                }
            }
            Rule::STANDARD => {
                // LOOKAHEAD(2) <LEFTPAREN> <STANDARD>
                // for (int i=0; i<table.fields.size(); i++)
                //   proc.inputs.addElement(table.fields.elementAt(i));
                for field in &table.fields {
                    let mut input_field = field.clone();
                    input_field.is_in = true;
                    proc.inputs.push(input_field);
                }
            }
            Rule::RIGHTPAREN => {
                // Skip closing parenthesis
            }
            _ => {}
        }
    }
    Ok(())
}

// JavaCC-style jOutputType function - matches JavaCC exactly
fn parse_j_output_type_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc, table: &Table) -> Result<(), Box<dyn std::error::Error>> {
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::LEFTPAREN => {
                // Skip opening parenthesis
            }
            Rule::SINGLE => {
                // LOOKAHEAD(2) <LEFTPAREN> <SINGLE>
                proc.is_single = true;
            }
            Rule::UPDATE => {
                // (<UPDATE> { proc.hasUpdates = true; })?
                proc.has_updates = true;
            }
            Rule::number => {
                // LOOKAHEAD(2) <LEFTPAREN> n = jNumber() <RIGHTPAREN>
                if let Ok(num) = inner_pair.as_str().parse::<i32>() {
                    proc.no_rows = Some(num);
                }
            }
            Rule::STANDARD => {
                // LOOKAHEAD(2) <LEFTPAREN> <STANDARD>
                // for (int i=0; i<table.fields.size(); i++)
                //   proc.outputs.addElement(table.fields.elementAt(i));
                for field in &table.fields {
                    let mut output_field = field.clone();
                    output_field.is_out = true;
                    proc.outputs.push(output_field);
                }
            }
            Rule::RIGHTPAREN => {
                // Skip closing parenthesis
            }
            _ => {}
        }
    }
    Ok(())
}

/// JavaCC jNewData() equivalent - creates a new data proc and processes DATALINE tokens
fn parse_j_new_data_into(pair: pest::iterators::Pair<Rule>) -> Result<Proc, Box<dyn std::error::Error>> {
    let mut proc = Proc {
        name: String::new(),
        is_proc: false,
        is_sproc: false,
        is_built_in: false,
        is_update: false,
        is_single: false,
        is_std: false,
        has_returning: false,
        use_std: false,
        extends_std: false,
        comments: Vec::new(),
        options: Vec::new(),
        inputs: Vec::new(),
        outputs: Vec::new(),
        lines: Vec::new(),
        fields: Vec::new(),
        start_line: Some(1),
        table: None,
        row_count: None,
        is_multiple_input: false,
        no_rows: None,
        has_updates: false,
        is_sql: false,
        dynamics: Vec::new(),
        dynamic_sizes: Vec::new(),
        is_data: true,  // JavaCC: proc.isData = true
        is_idl_code: false,
        update_fields: Vec::new(),
        order_fields: Vec::new(),
        dynamic_strung: Vec::new(),
    };
    
    // Process the first DATALINE token - matches JavaCC t = <DATALINE>
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::data_line => {
                let line_content = inner_pair.as_str().trim();
                if !line_content.is_empty() {
                    // JavaCC: Line l1 = new Line(..., new SQLProcStringToken(t.image.trim()))
                    proc.lines.push(line_content.to_string());
                }
            }
            _ => {}
        }
    }
    
    Ok(proc)
}

/// JavaCC jIdlCode() equivalent - creates a new IDL code proc and processes IDLLINE tokens  
fn parse_j_idl_code_into(pair: pest::iterators::Pair<Rule>) -> Result<Proc, Box<dyn std::error::Error>> {
    let mut proc = Proc {
        name: String::new(),
        is_proc: false,
        is_sproc: false,
        is_built_in: false,
        is_update: false,
        is_single: false,
        is_std: false,
        has_returning: false,
        use_std: false,
        extends_std: false,
        comments: Vec::new(),
        options: Vec::new(),
        inputs: Vec::new(),
        outputs: Vec::new(),
        lines: Vec::new(),
        fields: Vec::new(),
        start_line: Some(1),
        table: None,
        row_count: None,
        is_multiple_input: false,
        no_rows: None,
        has_updates: false,
        is_sql: false,
        dynamics: Vec::new(),
        dynamic_sizes: Vec::new(),
        is_data: false,
        is_idl_code: true,  // JavaCC: proc.isIdlCode = true
        update_fields: Vec::new(),
        order_fields: Vec::new(),
        dynamic_strung: Vec::new(),
    };
    
    // Process the first IDLLINE token - matches JavaCC t = <IDLLINE>
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::idl_line => {
                let line_content = inner_pair.as_str().trim();
                if !line_content.is_empty() {
                    // JavaCC: Line l1 = new Line(..., new SQLProcStringToken(t.image.trim()))
                    proc.lines.push(line_content.to_string());
                }
            }
            _ => {}
        }
    }
    
    Ok(proc)
}

/// JavaCC jOptSize() equivalent - parses optional size specification
fn parse_dynamic_identifier_with_size_into(pair: pest::iterators::Pair<Rule>, proc: &mut Proc) -> Result<(), Box<dyn std::error::Error>> {
    let mut identifier = String::new();
    let mut size = 256; // Default size - matches JavaCC jOptSize() default
    
    for inner_pair in pair.into_inner() {
        match inner_pair.as_rule() {
            Rule::identifier => {
                identifier = inner_pair.as_str().to_string();
            }
            Rule::opt_size => {
                size = parse_opt_size(inner_pair)?;
            }
            _ => {}
        }
    }
    
    if !identifier.is_empty() {
        // Add to dynamics if not already present - matches JavaCC !proc.hasDynamic(s)
        if !proc.has_dynamic(&identifier) {
            if proc.extends_std {
                proc.use_std = false; // JavaCC: if (proc.extendsStd == true) proc.useStd = false;
            }
            proc.dynamics.push(identifier);
            proc.dynamic_sizes.push(size);
            proc.dynamic_strung.push(false); // Default to not strung
        }
    }
    
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_debug_updateby_parsing() {
        // Test just the UPDATEBY keyword recognition
        let input_minimal = r#"
            DATABASE TestDB
            SERVER "localhost"
            TABLE Users
                id int
                PROC TestProc UPDATEBY
        "#;
        
        let result_minimal = parse_database(input_minimal);
        if result_minimal.is_err() {
            println!("Parse error for minimal UPDATEBY: {:?}", result_minimal.as_ref().err());
        }
        
        // If that fails, let's try an even simpler test
        let input_simple = r#"
            DATABASE TestDB
            SERVER "localhost"
            TABLE Users
                id int
                PROC TestProc INSERT
        "#;
        
        let result_simple = parse_database(input_simple);
        if result_simple.is_err() {
            println!("Parse error for INSERT: {:?}", result_simple.as_ref().err());
        }
        assert!(result_simple.is_ok(), "Failed to parse INSERT: {:?}", result_simple.err());
        
        // Now test the original UPDATEBY
        let input3 = r#"
            DATABASE TestDB
            SERVER "localhost"
            TABLE Users
                id int
                PROC UpdateById UPDATEBY id
        "#;
        
        let result3 = parse_database(input3);
        if result3.is_err() {
            println!("Parse error for UPDATEBY: {:?}", result3.as_ref().err());
        }
        assert!(result3.is_ok(), "Failed to parse UPDATEBY: {:?}", result3.err());
    }

    #[test]
    fn test_basic_database_parsing() {
        let input = r#"
            DATABASE TestDB
            FLAGS "flag1" "flag2"
            PACKAGE com.example.test
            OUTPUT "output_dir"
            IMPORT "import1"
            SERVER "localhost"
            SCHEMA "test_schema"
            USERID testuser
            PASSWORD testpass
            TABLE Users
                id int
        "#;
        
        let result = parse_database(input);
        assert!(result.is_ok());
        
        let db = result.unwrap();
        assert_eq!(db.name, "TestDB");
        assert_eq!(db.flags.len(), 2);
        assert_eq!(db.package_name, Some("com.example.test".to_string()));
        assert_eq!(db.server, "\"localhost\"");
        assert_eq!(db.schema, Some("\"test_schema\"".to_string()));
        assert_eq!(db.userid, "testuser");
        assert_eq!(db.password, "testpass");
    }

    #[test]
    fn test_debug_complex_multiple_procs() {
        let input = r#"
            DATABASE TestDB
            SERVER "localhost"
            TABLE Orders
                id bigidentity
                customer_id int
                status char(20)
                created_date datetime
                PROC InsertOrder INSERT RETURNING
                PROC UpdateOrder UPDATE
                PROC SelectByCustomer SELECTBY customer_id
                PROC SelectByStatus SELECTBY status IN ORDER created_date
        "#;
        
        let result = parse_database(input);
        if result.is_err() {
            println!("Parse error: {:?}", result.as_ref().err());
        }
        assert!(result.is_ok(), "Failed to parse database: {:?}", result.err());
        
        let db = result.unwrap();
        let table = &db.tables[0];
        
        println!("Number of procedures parsed: {}", table.procs.len());
        for (i, proc) in table.procs.iter().enumerate() {
            println!("Proc {}: {} (built_in: {})", i, proc.name, proc.is_built_in);
        }
        
        assert_eq!(table.procs.len(), 4);
    }
    
    #[test]
    fn test_user_defined_procedures() {
        let input = r#"
            DATABASE TestDB
            SERVER "localhost"
            TABLE Users
                id int
                username char(50)
                email char(100)
                status byte
                PROC CustomUserProc
                    INPUT
                        search_term char(100)
                        result_count int
                    CODE
                        "SELECT COUNT(*) FROM Users WHERE username LIKE ?"
                    ENDCODE
                PROC StandardUserProc
                    CODE
                        "SELECT * FROM Users"
                    ENDCODE
        "#;
        
        let result = parse_database(input);
        assert!(result.is_ok(), "Failed to parse database: {:?}", result.err());
        
        let db = result.unwrap();
        let table = &db.tables[0];
        
        // Check that we have 2 procedures
        assert_eq!(table.procs.len(), 2);
        
        // Check first procedure (user-defined with fields and code)
        let proc1 = &table.procs[0];
        assert_eq!(proc1.name, "CustomUserProc");
        assert!(!proc1.is_built_in);
        
        // Check second procedure (simple user-defined)
        let proc2 = &table.procs[1];
        assert_eq!(proc2.name, "StandardUserProc");
        assert!(!proc2.is_built_in);
    }

    #[test]
    fn test_javacc_helper_functions() {
        let input = r#"
            DATABASE TestDB
            SERVER "localhost"
            TABLE Users
                id int
                username char(50)
                email char(100)
                status byte
                PROC TestProc SELECT
                    INPUT
                        search_term char(100)
                    OUTPUT
                        id int
                        username char(50)
                    CODE
                        "SELECT id, username FROM Users WHERE username LIKE ?"
                    ENDCODE
        "#;
        
        let result = parse_database(input);
        assert!(result.is_ok(), "Failed to parse database: {:?}", result.err());
        
        let db = result.unwrap();
        let table = &db.tables[0];
        let proc = &table.procs[0];
        
        // Test that the procedure was parsed correctly
        assert_eq!(proc.name, "TestProc");
        assert!(!proc.is_built_in);
        assert!(proc.use_std);
        assert!(proc.extends_std);
        
        // Test that input fields were parsed
        assert_eq!(proc.inputs.len(), 1);
        assert_eq!(proc.inputs[0].name, "search_term");
        
        // Test that output fields were parsed
        assert_eq!(proc.outputs.len(), 2);
        assert_eq!(proc.outputs[0].name, "id");
        assert_eq!(proc.outputs[1].name, "username");
        
        // Test that the helper methods work correctly
        assert!(proc.has_input("search_term"));
        assert!(!proc.has_input("nonexistent"));
        assert!(proc.has_output("id"));
        assert!(!proc.has_output("nonexistent"));
        assert!(!proc.has_dynamic("test_dynamic"));
        assert!(!proc.has_fields("test_field"));
        assert!(!proc.has_update_fields("test_field"));
        assert!(!proc.has_orders("test_field"));
    }
} 
