#Project information
site_name: JPortal2
site_description: Portal2 is the newest version of the JPortal SI-file based generator.


# Repository
repo_name: SI-Gen/jportal2
repo_url: https://github.com/SI-Gen/jportal2

# Copyright
copyright: Copyright &copy; 2021

# Configuration
theme:
  name: material
  language: en
  logo: img/vanguard-logo-whiteonly.svg
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.top
    # - header.autohide
    #- navigation.expand
    - navigation.indexes
    - navigation.instant
    #- navigation.sections
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Extras
#extra:
#  social:
#    - icon: fontawesome/brands/github-alt
#      link: https://github.com/ramitsurana
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/ramitsurana
#    - icon: fontawesome/brands/linkedin
#      link: https://linkedin.com/in/ramitsurana

## Google Analytics
#google_analytics:
#  - UA-71344758-5
#  - auto
# leave out nave to genreate from folder structure
#nav:
#  - Home: README.md
#  - Getting Started:
#      - Installing Appsets : gettingstarted/setup.md
#  - User Manual:
#    - Chart Modules: charts/modules/main.md
#    - Chart Boostrap: charts/bootstrap/main.md
#  - Releases: releases.md

nav:
  - Home: 'README.md'
  - 'Installation':
      - 'Installing JPortal2': 'Overview/installing-jportal2.md'
      - 'Installing the JPortal2 VSCode extension': 'Overview/installing-vscode-jportal2-extension.md'
#      - 'Quickstarts':
#          - 'Quickstart with PostgreSQL': ''
#          - 'Quickstart with SQLServer': ''
#          - 'Quickstart with Oracle': ''
#          - 'Quickstart with DB2': ''
  - Tutorials:
      - 'Getting Started - installing prerequisites': 'Tutorials/getting-started.md'
      - 'Setting up our project directory & installing the SQLTools extension': 'Tutorials/setting-up-the-project-directory-and-sqltools-extension.md'
      - 'Creating our first table definition': 'Tutorials/creating-our-first-table-definition.md'
      - 'Generating PostgreSQL DDL': 'Tutorials/generating-postgres-ddl.md'
      - 'Generating Python code': 'Tutorials/generating-python-code.md'
      - 'Adding an additional table and foreign keys': 'Tutorials/adding-an-additional-table.md'
      - 'Additional Built-In Queries': 'Tutorials/additional-built-in-queries.md'
      - 'Custom Queries and Advanced functionality': 'Tutorials/custom-queries.md'
      - 'Summary': 'Tutorials/summary.md'
  - Quickstarts:
      - 'Quickstart with PostgreSQL': 'Quickstarts/Quickstart with Postgres.md'
  - "How-to guides":
      - 'Retrieving rows': 'Howto/retrieving-rows.md'
      - 'Inserting rows': "Howto/inserting-rows.md"
      - 'Updating rows': "Howto/updating-rows.md"
      - 'Deleting rows': "Howto/deleting-rows.md"
      - 'Counting rows': "Howto/counting-rows.md"
      - 'Checking if a record exists': "Howto/checking-if-rows-exist.md"
      - 'Custom procs': 'Howto/custom-procs.md'
      - 'Dynamic SQL': 'Howto/dynamic-sql.md'
      - 'Using enums': 'Howto/using-enums.md'
      - 'Using literals': 'Howto/using-literals.md'
      - 'Using keys, indexes and foreign keys': 'Howto/using-keys-indexes-and-foreign-keys.md'
      - 'Using Grants': 'Howto/using-grants.md'

  - 'Reference':
      - 'Column types' : 'Reference/column-types.md'
      - 'Command-Line Interface': 'Reference/cli.md'
      - 'Configuration file' : 'Reference/configuration-file.md'
      - 'Freemarker template' : 'Reference/Freemarker template.md'

  - 'F.A.Q.': 'faq.md'

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
      #- anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys

plugins:
  - search # necessary for search to work
  #- glightbox # To allow zooming of images
