#Project information
site_name: JPortal2
site_description: Portal2 is the newest version of the JPortal SI-file based generator.


# Repository
repo_name: SI-Gen/jportal2
repo_url: https://github.com/SI-Gen/jportal2

# Copyright
copyright: Copyright &copy; 2021

# Configuration
theme:
  name: material
  language: en
  features:
    - tabs
    - instant
  palette:
    primary: red
    accent: reds
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: assest/metisiconsmall.png
    repo: material/ship-wheel
  favicon: assest/metisiconsmall.png
  logo: assest/metisiconsmall.png

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ramitsurana
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ramitsurana
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ramitsurana

## Google Analytics
#google_analytics:
#  - UA-71344758-5
#  - auto
# leave out nave to genreate from folder structure
#nav:
#  - Home: README.md
#  - Getting Started:
#      - Installing Appsets : gettingstarted/setup.md
#  - User Manual:
#    - Chart Modules: charts/modules/main.md
#    - Chart Boostrap: charts/bootstrap/main.md
#  - Releases: releases.md
# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search # necessary for search to work