name: Build

on: [push]
jobs:
  build:
    name: 'Build Repo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: 'Cache Maven packages'
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: 'Build with Maven'
        run: mvn --batch-mode --update-snapshots verify

  prelease_jar:
#    if: github.event.pull_request.merged == 'true'
    name: 'Upload Pre-release Jar To GitHub'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Bump and Tag Version
        id: version_bump
        uses: jefflinse/pr-semver-bump@v1
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major release
          minor-label: minor release
          patch-label: patch release
          require-release-notes: false
          release-notes-prefix: ''
          release-notes-suffix: ''
          with-v: false


      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Changes Maven Version
      - name: 'Change Maven Version'
        run: |
          mvn versions:set -DnewVersion=${{ steps.version_bump.outputs.version }}

      # Generate Jar File
      - name: 'Generate Jar'
        run: mvn package -Dmaven.javadoc.skip=true -DskipTests -DskipITs  -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      # Upload Jar File
      - name: 'Upload Jar Files to Release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/jportal2-${{ steps.version_bump.outputs.version }}.jar
          asset_name: jportal2-${{ steps.version_bump.outputs.version }}.jar
          tag: ${{ steps.version_bump.outputs.version }}
          overwrite: true
          body: 'JPortal2 - Pre-Release<br/><br/><b>Change Log<b><br/>${{steps.github_release.outputs.changelog}}'




