name: Build

on: [push]
jobs:
  build:
    name: 'Build Repo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: 'Cache Maven packages'
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: 'Build with Maven'
        run: mvn --batch-mode --update-snapshots verify

  prelease_jar:
    name: 'Upload Pre-release Jar To GitHub'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: 'Retrieve Tag'
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: "Jportal-"

      - name: 'Create a Pre-Release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_version }}
          release_name: ${{ steps.tag_version.outputs.new_version }}
          body: 'Pre-Release - ${{ steps.tag_version.outputs.new_version }}'
          prerelease: true


      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Changes Maven Version
      - name: 'Change Maven Version'
        run: |
          mvn versions:set -DnewVersion=${{ steps.tag_version.outputs.new_version }}

      # Generate Jar File
      - name: 'Generate Jar'
        run: mvn package -Dmaven.javadoc.skip=true -DskipTests -DskipITs  -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      # Upload Jar File
      - name: 'Upload Jar Files to Release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/jportal2-${{ steps.tag_version.outputs.new_version }}.jar
          asset_name: jportal2-${{ steps.tag_version.outputs.new_version }}.jar
          tag: ${{ steps.tag_version.outputs.new_version }}
          overwrite: true
          body: 'JPortal2 - Pre-Release<br/><br/><b>Change Log<b><br/>${{steps.github_release.outputs.changelog}}'



