name: HouseKeeping
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      last_commit_age_days:
        description: 'Number of days since last commit'
        required: false
        default: '100'


#A branch must meet all the following criteria to be deemed abandoned and safe to delete:
#
#  Must NOT be the default branch (eg master or main, depending on your repository settings)
#  Must NOT be a protected branch
#  Must NOT have any open pull requests
#  Must NOT be the base of an open pull request of another branch. The base of a pull request is the branch you told GitHub you want to merge your pull request into.
#  Must NOT be in an optional list of branches to ignore
#  Must be older than a given amount of days

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: Satisfy my repo CDO
    steps:
      - name: Delete those pesky dead branches
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v1
        id: delete_stuff
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: ${{github.event.inputs.last_commit_age_days}}
          ignore_branches: develop,master

          # Disable dry run and actually get stuff deleted
#          dry_run: no

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete_stuff.outputs.deleted_branches }}'"