name: Release

on:
  workflow_dispatch:
    inputs:
      release_description:
        description: 'Description'
        required: false
        default: 'JPortal2 Release'
      release_type:
        description: 'Release Type (patch, minor, major)'
        required: true
        default: 'minor'

jobs:
  build:
    name: 'Building Repo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build and Test'
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"

  maven_release:
    name: 'Maven Release'
    runs-on: ubuntu-latest
    needs: build
    if: "!contains(github.event.head_commit.message, '[Github-Bot]')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Retrieve & Bump Tag'
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{github.event.inputs.release_type}}
          tag_prefix: ''

      - name: 'Echo Release'
        run: echo ${{ steps.tag_version.outputs.new_tag }}
          
      - name: 'GitHub release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          body: '${{github.event.inputs.release_description}} - ${{ steps.tag_version.outputs.new_tag }}'

      - name: 'Maven Release'
        uses: qcastel/github-actions-maven-release@master
        env:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/

        with:
          release-branch-name: 'master'
          git-release-bot-name: 'bbd-github-bot'
          git-release-bot-email: 'bbdgithubbot@gmail.com'

          maven-args: '-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip -Prelease-oss-maven-central'
#          maven-development-version-number: ${{ steps.tag_version.outputs.new_tag  }}-SNAPSHOT
          maven-release-version-number: ${{ steps.tag_version.outputs.new_tag  }}

          maven-repo-server-id: ossrh
          maven-repo-server-username: ${{ secrets.MVN_REPO_PRIVATE_REPO_USER }}
          maven-repo-server-password: ${{ secrets.MVN_REPO_PRIVATE_REPO_PASSWORD }}

          gpg-enabled: 'false'