name: Release 2.0

on:
  workflow_dispatch:
    inputs:
      release_description:
        description: 'Description'
        required: false
        default: 'JPortal2 - Release'
      release_type:
        description: 'Next Maven Release Version (patch, minor, major)'
        required: true
        default: 'patch'

jobs:
  publish:
    environment: mavenCentralPublish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup Maven settings
        uses: s4u/maven-settings-action@v2.4.0
        with:
          servers: '[{"id": "ossrh", "username": "${{ secrets.MVN_USERNAME }}", "password": "${{ secrets.MVN_PASSPHRASE }}"}]'
      - name: Publish to Maven Central
        env:
          SIGN_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn clean package -Prelease-oss-maven-central -Dmaven.test.skip=true sign:sign nexus-staging:deploy -B