name: Release

on:
  workflow_dispatch:
    inputs:
      release_description:
        description: 'Description'
        required: false
        default: 'JPortal2 Release'
      release_type:
        description: 'Release Type (patch, minor, major)'
        required: true
        default: 'minor'

jobs:
  maven_release:
    name: 'Maven Release'
    runs-on: ubuntu-latest
    needs: build
    if: "!contains(github.event.head_commit.message, '[Github-Bot]')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Retrieve & Bump Tag'
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{github.event.inputs.release_type}}
          tag_prefix: ''

      - name: Change something
        run: |
          mvn versions:set -DnewVersion=${{ steps.tag_version.outputs.new_tag }}-SNAPSHOT

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_prefix: "[Github-Bot]"
          commit_message: "Changed Maven version"
          target_branch: update/version
          
      - name: 'GitHub release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          body: '${{github.event.inputs.release_description}} - ${{ steps.tag_version.outputs.new_tag }}'