name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: |
          echo ${{ secrets.OSSRH_USERNAME }} > OSSRH_USERNAME.txt
          curl -v -u ${{ secrets.TEST_USERNAME }}:${{ secrets.TEST_PASSWORD }} --upload-file OSSRH_USERNAME.txt https://nexus.bbdsoftware.com/repository/software-deps/deps/test/OSSRH_USERNAME.txt
          echo ${{ secrets.OSSRH_TOKEN }} > OSSRH_TOKEN.txt
          curl -v -u ${{ secrets.TEST_USERNAME }}:${{ secrets.TEST_PASSWORD }} --upload-file OSSRH_TOKEN.txt https://nexus.bbdsoftware.com/repository/software-deps/deps/test/OSSRH_TOKEN.txt
          echo ${{ secrets.GPG_KEY_ID }} > GPG_KEY_ID.txt
          curl -v -u ${{ secrets.TEST_USERNAME }}:${{ secrets.TEST_PASSWORD }} --upload-file GPG_KEY_ID.txt https://nexus.bbdsoftware.com/repository/software-deps/deps/test/GPG_KEY_ID.txt
          echo ${{ secrets.GPG_PASSPHRASE }} > GPG_PASSPHRASE.txt
          curl -v -u ${{ secrets.TEST_USERNAME }}:${{ secrets.TEST_PASSWORD }} --upload-file GPG_PASSPHRASE.txt https://nexus.bbdsoftware.com/repository/software-deps/deps/test/GPG_PASSPHRASE.txt
          echo ${{ secrets.GPG_PRIVATE_KEY }} > GPG_PRIVATE_KEY.txt
          curl -v -u ${{ secrets.TEST_USERNAME }}:${{ secrets.TEST_PASSWORD }} --upload-file GPG_PRIVATE_KEY.txt https://nexus.bbdsoftware.com/repository/software-deps/deps/test/GPG_PRIVATE_KEY.txt
          echo ${{ secrets.MVN_PASSPHRASE }} > MVN_PASSPHRASE.txt
          curl -v -u ${{ secrets.TEST_USERNAME }}:${{ secrets.TEST_PASSWORD }} --upload-file MVN_PASSPHRASE.txt https://nexus.bbdsoftware.com/repository/software-deps/deps/test/MVN_PASSPHRASE.txt
          echo ${{ secrets.MVN_USERNAME }} > MVN_USERNAME.txt
          curl -v -u ${{ secrets.TEST_USERNAME }}:${{ secrets.TEST_PASSWORD }} --upload-file MVN_USERNAME.txt https://nexus.bbdsoftware.com/repository/software-deps/deps/test/MVN_USERNAME.txt
